---
name: Pull Request

on:
  push:
    branches: [devel]
  pull_request:
    branches: [devel]

jobs:
  pull_request:
    runs-on: ubuntu-latest
    name: pull_request
    env:
      DOCKER_API_VERSION: "1.38"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          pip install \
            molecule \
            molecule-docker \
            yamllint \
            ansible-lint \
            openshift \
            jmespath \
            ansible
          wget -O /usr/local/bin/operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/v0.19.4/operator-sdk-v0.19.4-x86_64-linux-gnu
          chmod +x /usr/local/bin/operator-sdk
      - name: Install collections
        run: |
          ansible-galaxy collection install community.kubernetes operator_sdk.util
      - name: Run Molecule
        env:
          MOLECULE_VERBOSITY: 3
        run: |
          molecule test -s test-local
      - name: Build Image
        run: |
          operator-sdk build quay.io/ansible/operator-sdk:${GITHUB_SHA::8}
      - name: Get Images
        run: |
          docker images
